# Generated by Django 5.0.7 on 2024-07-30 23:24

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=api.models.idHash, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, default='', upload_to='assets/products')),
                ('url', models.URLField(blank=True, default='')),
                ('price', models.CharField(blank=True, default='', max_length=20)),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
